# Generated by Django 5.0.1 on 2024-07-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=256)),
                ('nickName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('photo', models.TextField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
