# Generated by Django 4.1.13 on 2024-08-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_id'),
    ]

    operations = [
    ]
