# Generated by Django 5.0.1 on 2024-07-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='team2',
        ),
    ]
