# Generated by Django 5.0.1 on 2024-07-28 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_remove_bet_team1_remove_bet_team2'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='matchId',
        ),
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='match.match'),
        ),
    ]
