# Generated by Django 5.0.1 on 2024-07-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ExactAward',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='match',
            name='directionAward',
            field=models.IntegerField(default=1),
        ),
    ]
